// Explicit ownership inventory. Account identity/authentication and public
// product catalogs remain global; all learning and workspace operations do not.
const WORKSPACE_MODELS = {
  StandingClanRequest: 'standing_clan_requests',
  Skill: 'skills',
  OpenSourceOrg: 'open_source_orgs',
  ProductUpdate: 'product_updates',
  ActivitySession: 'activity_sessions',
  AdaptiveRecommendation: 'adaptive_recommendations',
  AnalyticsEvent: 'analytics_events',
  MenteeAnalytics: 'mentee_analytics',
  MentorAnalytics: 'mentor_analytics',
  ProgramAnalytics: 'program_analytics',
  SkillAssessment: 'skill_assessments',
  TaskAnalytics: 'task_analytics',
  Challenge: 'challenges',
  Gift: 'gifts',
  Redemption: 'redemptions',
  UserChallenge: 'user_challenges',
  Assessment: 'assessments',
  AssessmentQuestion: 'assessment_questions',
  AssessmentSubmission: 'assessment_submissions',
  CohortAssessment: 'cohort_assessments',
  RubricSnippet: 'rubric_snippets',
  InterviewAnswer: 'interview_answers',
  InterviewAssignment: 'interview_assignments',
  InterviewKit: 'interview_kits',
  InterviewQuestion: 'interview_questions',
  InterviewSession: 'interview_sessions',
  MessageAttachment: 'message_attachments',
  MessageReaction: 'message_reactions',
  ClanChangeRequest: 'clan_change_requests',
  ClanJoinRequest: 'clan_join_requests',
  ClanMemberPermission: 'clan_member_permissions',
  CrossClanAssignment: 'cross_clan_assignments',
  ProgramReview: 'program_reviews',
  EmailQueue: 'email_queue',
  AIEvaluationQueue: 'ai_evaluation_queue',
  QuizAnswer: 'quiz_answers',
  QuizAssignment: 'quiz_assignments',
  QuizKit: 'quiz_kits',
  QuizQuestion: 'quiz_questions',
  QuizSession: 'quiz_sessions',
  AdminMeeting: 'admin_meetings',
  AvailabilityRule: 'availability_rules',
  AvailabilitySlot: 'availability_slots',
  CohortReviewEntry: 'cohort_review_entries',
  CohortReviewSession: 'cohort_review_sessions',
  CohortReviewUnlockGrant: 'cohort_review_unlock_grants',
  CohortReviewUnlockRequest: 'cohort_review_unlock_requests',
  MeetingNote: 'meeting_notes',
  MenteeSchedule: 'mentee_schedules',
  ReviewSchedule: 'review_schedules',
  ScheduleTemplate: 'schedule_templates',
  ScheduledMeeting: 'scheduled_meetings',
  AnnouncementReaction: 'announcement_reactions',
  CommunityComment: 'community_comments',
  CommunityReaction: 'community_reactions',
  CommunityReport: 'community_reports',
  FeedbackReport: 'feedback_reports',
  FileUpload: 'file_uploads',
  ScheduledJob: 'scheduled_jobs',
  DailyLogEntry: 'daily_log_entries',
  DelayEvent: 'delay_events',
  FeedbackSnippet: 'feedback_snippets',
  MentorMenteeMatch: 'mentor_mentee_matches',
  RoadmapLink: 'roadmap_links',
  RoadmapProgress: 'roadmap_progress',
  TaskFeedback: 'task_feedback',
  TaskProgressEntry: 'task_progress_entries',
  TaskResource: 'task_resources',
  TaskSkill: 'task_skills',
  TaskSubmissionFile: 'task_submission_files',
  Track: 'tracks',
  AdminProfile: 'admin_profiles',
  Collaborator: 'collaborators',
  Insight: 'insights',
  MenteeProfile: 'mentee_profiles',
  MentorProfile: 'mentor_profiles',
  PerformanceNomination: 'performance_nominations',
  PromotionCandidate: 'promotion_candidates',
  UserSkill: 'user_skills',
  MentorStyleProfile: 'mentor_style_profiles',
  KnowledgeChunk: 'knowledge_chunks',
  RagIngestionJob: 'rag_ingestion_jobs',
  MessageDraft: 'message_drafts',
  MentorEditHistory: 'mentor_edit_histories',
};

const GLOBAL_MODELS = new Set([
  'User', 'Organization', 'Plan',
  'SuppressedEmail', 'DeviceToken', 'UserSettings', 'UserSession', 'RefreshToken',
  'SignInLinkToken', 'PasswordResetToken', 'EmailVerificationToken', 'TwoFactorAuth',
]);

module.exports = { WORKSPACE_MODELS, GLOBAL_MODELS };
